export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const SEARCH_PATIENT = "SEARCH_PATIENT";
export const SEARCH_DOCTOR = "SEARCH_DOCTOR";

export const GET_ALL_DOCTORS = "GET_ALL_DOCTORS";
export const GET_ALL_PATIENTS = "GET_ALL_PATIENTS";

export const GET_APPOINTMENT_FOR_ID = "GET_APPOINTMENT_FOR_ID";
export const BOOK_APPOINTMENT = "BOOK_APPOINTMENT";
export const GET_APPOINTMENT_FOR_DOCTOR_ID = "GET_APPOINTMENT_FOR_DOCTOR_ID";
export const GET_APPOINTMENT_FOR_PATIENT_ID = "GET_APPOINTMENT_FOR_PATIENT_ID";
export const APPROVE_APPOINTMENT_BY_ID = "APPROVE_APPOINTMENT_BY_ID";
export const DELETE_APPOINTMENT_BY_ID = "DELETE_APPOINTMENT_BY_ID";
export const ADD_PRESCRIPTION_TO_APPOINTMENT = "ADD_PRESCRIPTION_TO_APPOINTMENT";
export const END_APPOINTMENT = "END_APPOINTMENT";

export const ADD_PRESCRIPTION = "ADD_PRESCRIPTION";
export const GET_PRESCRIPTION_FOR_APPOINTMENT = "GET_PRESCRIPTION_FOR_APPOINTMENT"

export const PATIENT_PRESCRIPTIONS = "PATIENT_PRESCRIPTIONS"

export const ADD_USER_DATA = "ADD_USER_DATA";
export const GET_USER_DATA = "GET_USER_DATA"